export const onboarding = {
  "onboarding.back":"Back","onboarding.continue":"Continue","onboarding.retry":"Retry",
  "onboarding.progress":"Step {{current}} of {{total}}","onboarding.step.welcome":"Welcome","onboarding.step.personalization":"Personalize","onboarding.step.steam":"Steam","onboarding.step.library":"Library",
  "onboarding.welcome.title":"Welcome to Achievement Nexus","onboarding.welcome.body":"Your games are only the beginning. Track achievements, discover what to unlock next, and turn every game into a journey.","onboarding.welcome.start":"Start Your Journey",
  "onboarding.personalize.eyebrow":"Make it yours","onboarding.personalize.title":"Choose your experience","onboarding.personalize.preview":"Live preview",
  "onboarding.steam.title":"Connect your Steam library","onboarding.steam.body":"SteamID64 identifies your public library. A Web API key is needed to request it from Steam.","onboarding.steam.id":"SteamID64","onboarding.steam.key":"Steam Web API key","onboarding.steam.privacy":"The key is passed to Rust memory for this session and is not stored by Achievement Nexus.","onboarding.steam.connect":"Test and connect","onboarding.steam.checking":"Checking…","onboarding.steam.connected":"Connected successfully","onboarding.steam.skip":"Skip for now",
  "onboarding.steam.error.invalidId":"Enter a valid 17-digit SteamID64.","onboarding.steam.error.invalidKey":"The Steam Web API key is missing or invalid.","onboarding.steam.error.private":"Steam could not access this profile or library. Check its privacy settings.","onboarding.steam.error.network":"Steam could not be reached. Check your connection and retry.","onboarding.steam.error.timeout":"Steam took too long to respond. Please retry.","onboarding.steam.error.rateLimit":"Steam is receiving too many requests. Wait briefly and retry.","onboarding.steam.error.generic":"The connection could not be verified. Please retry.",
  "onboarding.library.eyebrow":"Final step","onboarding.library.title":"Bring in your library","onboarding.library.ready":"You're ready.","onboarding.library.connectedBody":"Import the games currently available through your connected Steam profile.","onboarding.library.skippedBody":"You can connect Steam later from Settings and start using the app now.","onboarding.library.sync":"Sync library","onboarding.library.syncing":"Syncing library…","onboarding.library.received":"Games received","onboarding.library.new":"New games","onboarding.library.updated":"Updated games","onboarding.library.skipped":"Skipped","onboarding.library.error":"Library sync failed. You can retry or enter the app safely.","onboarding.library.achievementsLater":"Achievements can be synced later from Game Details or Steam Settings.","onboarding.enter":"Enter Achievement Nexus","onboarding.saving":"Saving…"
} as const;
