export const onboarding = {
  "onboarding.back":"Back","onboarding.continue":"Continue","onboarding.retry":"Retry",
  "onboarding.progress":"Step {{current}} of {{total}}","onboarding.step.welcome":"Welcome","onboarding.step.personalization":"Personalize","onboarding.step.steam":"Steam","onboarding.step.library":"Library",
  "onboarding.welcome.title":"Welcome to Achievement Nexus","onboarding.welcome.body":"Your games are only the beginning. Track achievements, discover what to unlock next, and turn every game into a journey.","onboarding.welcome.start":"Start Your Journey",
  "onboarding.personalize.eyebrow":"Make it yours","onboarding.personalize.title":"Choose your experience","onboarding.personalize.preview":"Live preview",
  "onboarding.steam.title":"Connect your Steam library","onboarding.steam.body":"Sign in with Steam to bring your games and achievements into Nexus.","onboarding.steam.id":"Steam account ID","onboarding.steam.key":"Steam connection code","onboarding.steam.privacy":"Your sign-in details are used only while connecting and are never saved by Achievement Nexus.","onboarding.steam.connect":"Connect Steam","onboarding.steam.checking":"Connecting…","onboarding.steam.connected":"Steam connected","onboarding.steam.skip":"Skip for now",
  "onboarding.steam.error.invalidId":"Check your Steam account ID and try again.","onboarding.steam.error.invalidKey":"Please sign in to Steam again.","onboarding.steam.error.private":"Steam couldn't access this profile or library. Check its privacy settings.","onboarding.steam.error.network":"Couldn't reach Steam. Check your connection and try again.","onboarding.steam.error.timeout":"Steam took too long to respond. Try again.","onboarding.steam.error.rateLimit":"Steam is busy right now. Wait a moment and try again.","onboarding.steam.error.generic":"Couldn't connect to Steam. Try again.",
  "onboarding.library.eyebrow":"Final step","onboarding.library.title":"Bring in your library","onboarding.library.ready":"You're ready.","onboarding.library.connectedBody":"Import the games currently available through your connected Steam profile.","onboarding.library.skippedBody":"You can connect Steam later from Settings and start using the app now.","onboarding.library.sync":"Sync library","onboarding.library.syncing":"Syncing library…","onboarding.library.received":"Games received","onboarding.library.new":"New games","onboarding.library.updated":"Updated games","onboarding.library.skipped":"Skipped","onboarding.library.error":"Library sync failed. You can retry or enter the app safely.","onboarding.library.achievementsLater":"Achievements can be synced later from Game Details or Steam Settings.","onboarding.enter":"Enter Achievement Nexus","onboarding.saving":"Saving…"
} as const;
