export type ToolTrustKind="official"|"external"|"community";
export interface ToolRatingSummary{id?:string;average:number|null;total:number;distribution:Record<"1"|"2"|"3"|"4"|"5",number>}
export interface ToolBadge{id:string;name:string;slug:string;color:"purple"|"blue"|"green"|"amber"|"neutral";iconKey:string;displayOrder:number;isActive:boolean;archivedAt?:string;createdAt:string;updatedAt:string}
export interface ToolCategory{id:string;name:string;slug:string;description?:string;displayOrder:number;isActive:boolean;archivedAt?:string;createdAt:string;updatedAt:string}
export interface NexusTool{id:string;name:string;slug:string;shortDescription:string;fullDescription:string;version:string;developerName:string;externalDownloadUrl:string;downloadDomain:string;downloadTrust:ToolTrustKind;officialWebsiteUrl?:string;iconUrl?:string;coverUrl?:string;iconAssetId?:string;coverAssetId?:string;category?:ToolCategory;ratingSummary?:ToolRatingSummary;badges:ToolBadge[];isFeatured:boolean;isActive:boolean;archivedAt?:string;publishedAt?:string;createdAt:string;updatedAt:string}
export interface ToolDraft{name:string;slug:string;shortDescription:string;fullDescription:string;version:string;developerName:string;externalDownloadUrl:string;downloadTrust:ToolTrustKind;officialWebsiteUrl?:string;iconAssetId?:string;coverAssetId?:string;categoryId?:string;badgeIds:string[];isFeatured:boolean;isActive:boolean;publishedAt?:string}
export type ToolBadgeDraft=Pick<ToolBadge,"name"|"slug"|"color"|"iconKey"|"displayOrder"|"isActive">;
export type ToolCategoryDraft=Pick<ToolCategory,"name"|"slug"|"description"|"displayOrder"|"isActive">;
export type ToolReviewStatus="active"|"hidden"|"removed";
export type ToolReviewSort="newest"|"highest_rating"|"lowest_rating";
export type ToolReviewReason="spam"|"harassment"|"unsafe_link"|"misleading"|"inappropriate"|"other";
export type ToolReviewReportStatus="open"|"resolved"|"dismissed";
export interface ToolReviewDeveloperReply{body:string;createdAt:string;updatedAt:string;edited:boolean}
export interface ToolReviewView{id:string;toolId:string;userId:string;title?:string;body:string;status:ToolReviewStatus;createdAt:string;updatedAt:string;moderatedAt?:string;moderatedBy?:string;moderationReason?:string;edited:boolean;displayName:string;avatarUrl?:string;rating:number|null;helpfulCount:number;currentUserHelpful?:boolean;developerReply?:ToolReviewDeveloperReply}
export interface ToolReviewPage{items:ToolReviewView[];total:number;page:number;pageSize:number}
export interface ToolReviewAdminView{id:string;toolId:string;userId:string;displayName:string;title?:string;body:string;status:ToolReviewStatus;rating:number|null;reportsCount:number;tool:{id:string;name:string;slug:string};createdAt:string;updatedAt:string;developerReply?:ToolReviewDeveloperReply}
export interface ReviewHelpfulState{helpfulCount:number;currentUserHelpful:boolean}
export interface ToolReviewAdminPage{items:ToolReviewAdminView[];total:number;page:number;pageSize:number}
export interface ToolReviewReportView{id:string;reviewId:string;reporterUserId:string;reason:ToolReviewReason;details?:string;status:ToolReviewReportStatus;createdAt:string;resolvedAt?:string;resolvedBy?:string;reporterName:string;reporterAvatarUrl?:string;tool:{id:string;name:string;slug:string};review:{id:string;userId:string;authorName:string;title?:string;body:string;status:ToolReviewStatus;createdAt:string;updatedAt:string;moderatedAt?:string;moderatedBy?:string;moderationReason?:string}}
export interface ToolReviewReportPage{items:ToolReviewReportView[];total:number;page:number;pageSize:number}
export interface ToolFavoriteStats{views:number;downloadClicks:number;favorites:number}
export interface ToolFavoriteEntry{toolId:string;createdAtMs:number;stats:ToolFavoriteStats;tool:NexusTool}
export interface ToolCatalog{items:ToolCategory[]|ToolBadge[];total:number}
