export const onboarding = {
  "onboarding.back":"رجوع","onboarding.continue":"متابعة","onboarding.retry":"إعادة المحاولة",
  "onboarding.progress":"الخطوة {{current}} من {{total}}","onboarding.step.welcome":"مرحبًا","onboarding.step.personalization":"التخصيص","onboarding.step.steam":"Steam","onboarding.step.library":"المكتبة",
  "onboarding.welcome.title":"مرحبًا بك في Achievement Nexus","onboarding.welcome.body":"ألعابك ليست سوى البداية. تتبّع إنجازاتك، واكتشف هدفك التالي، واجعل كل لعبة رحلة تستحق الإكمال.","onboarding.welcome.start":"ابدأ رحلتك",
  "onboarding.personalize.eyebrow":"اجعلها تجربتك","onboarding.personalize.title":"اختر تجربتك","onboarding.personalize.preview":"معاينة مباشرة",
  "onboarding.steam.title":"اربط مكتبة Steam","onboarding.steam.body":"سجّل الدخول إلى Steam لإضافة ألعابك وإنجازاتك إلى Nexus.","onboarding.steam.id":"معرّف حساب Steam","onboarding.steam.key":"رمز اتصال Steam","onboarding.steam.privacy":"تُستخدم تفاصيل تسجيل الدخول أثناء الربط فقط، ولا يحفظها Achievement Nexus.","onboarding.steam.connect":"ربط Steam","onboarding.steam.checking":"جارٍ الاتصال…","onboarding.steam.connected":"تم ربط Steam","onboarding.steam.skip":"تخطَّ الآن",
  "onboarding.steam.error.invalidId":"تحقق من معرّف حساب Steam ثم حاول مجددًا.","onboarding.steam.error.invalidKey":"يرجى تسجيل الدخول إلى Steam مجددًا.","onboarding.steam.error.private":"تعذر على Steam الوصول إلى الملف أو المكتبة. تحقق من إعدادات الخصوصية.","onboarding.steam.error.network":"تعذر الوصول إلى Steam. تحقق من اتصالك ثم حاول مجددًا.","onboarding.steam.error.timeout":"استغرق رد Steam وقتًا طويلًا. حاول مجددًا.","onboarding.steam.error.rateLimit":"Steam مشغول الآن. انتظر قليلًا ثم حاول مجددًا.","onboarding.steam.error.generic":"تعذر الاتصال بـSteam. حاول مجددًا.",
  "onboarding.library.eyebrow":"الخطوة الأخيرة","onboarding.library.title":"استورد مكتبتك","onboarding.library.ready":"أصبحت جاهزًا.","onboarding.library.connectedBody":"استورد الألعاب المتاحة حاليًا عبر ملف Steam المتصل.","onboarding.library.skippedBody":"يمكنك ربط Steam لاحقًا من الإعدادات والبدء الآن.","onboarding.library.sync":"مزامنة المكتبة","onboarding.library.syncing":"جارٍ مزامنة المكتبة…","onboarding.library.received":"الألعاب المستلمة","onboarding.library.new":"ألعاب جديدة","onboarding.library.updated":"ألعاب محدّثة","onboarding.library.skipped":"تم تجاوزها","onboarding.library.error":"فشلت مزامنة المكتبة. يمكنك المحاولة مجددًا أو دخول التطبيق بأمان.","onboarding.library.achievementsLater":"يمكنك مزامنة الإنجازات لاحقًا من تفاصيل اللعبة أو إعدادات Steam.","onboarding.enter":"ادخل إلى Achievement Nexus","onboarding.saving":"جارٍ الحفظ…"
} as const;
