export const onboarding = {
  "onboarding.back":"رجوع","onboarding.continue":"متابعة","onboarding.retry":"إعادة المحاولة",
  "onboarding.progress":"الخطوة {{current}} من {{total}}","onboarding.step.welcome":"مرحبًا","onboarding.step.personalization":"التخصيص","onboarding.step.steam":"Steam","onboarding.step.library":"المكتبة",
  "onboarding.welcome.title":"مرحبًا بك في Achievement Nexus","onboarding.welcome.body":"ألعابك ليست سوى البداية. تتبّع إنجازاتك، واكتشف هدفك التالي، واجعل كل لعبة رحلة تستحق الإكمال.","onboarding.welcome.start":"ابدأ رحلتك",
  "onboarding.personalize.eyebrow":"اجعلها تجربتك","onboarding.personalize.title":"اختر تجربتك","onboarding.personalize.preview":"معاينة مباشرة",
  "onboarding.steam.title":"اربط مكتبة Steam","onboarding.steam.body":"يحدد SteamID64 مكتبتك العامة، ويُستخدم مفتاح Web API لطلبها من Steam.","onboarding.steam.id":"SteamID64","onboarding.steam.key":"مفتاح Steam Web API","onboarding.steam.privacy":"يُمرر المفتاح إلى ذاكرة Rust لهذه الجلسة ولا يخزنه Achievement Nexus.","onboarding.steam.connect":"اختبر الاتصال واربط","onboarding.steam.checking":"جارٍ التحقق…","onboarding.steam.connected":"تم الاتصال بنجاح","onboarding.steam.skip":"تخطَّ الآن",
  "onboarding.steam.error.invalidId":"أدخل SteamID64 صالحًا من 17 رقمًا.","onboarding.steam.error.invalidKey":"مفتاح Steam Web API مفقود أو غير صالح.","onboarding.steam.error.private":"تعذر على Steam الوصول إلى الملف أو المكتبة. تحقق من إعدادات الخصوصية.","onboarding.steam.error.network":"تعذر الوصول إلى Steam. تحقق من اتصالك ثم أعد المحاولة.","onboarding.steam.error.timeout":"استغرقت استجابة Steam وقتًا طويلًا. أعد المحاولة.","onboarding.steam.error.rateLimit":"تستقبل Steam طلبات كثيرة. انتظر قليلًا ثم أعد المحاولة.","onboarding.steam.error.generic":"تعذر التحقق من الاتصال. أعد المحاولة.",
  "onboarding.library.eyebrow":"الخطوة الأخيرة","onboarding.library.title":"استورد مكتبتك","onboarding.library.ready":"أصبحت جاهزًا.","onboarding.library.connectedBody":"استورد الألعاب المتاحة حاليًا عبر ملف Steam المتصل.","onboarding.library.skippedBody":"يمكنك ربط Steam لاحقًا من الإعدادات والبدء الآن.","onboarding.library.sync":"مزامنة المكتبة","onboarding.library.syncing":"جارٍ مزامنة المكتبة…","onboarding.library.received":"الألعاب المستلمة","onboarding.library.new":"ألعاب جديدة","onboarding.library.updated":"ألعاب محدّثة","onboarding.library.skipped":"تم تجاوزها","onboarding.library.error":"فشلت مزامنة المكتبة. يمكنك المحاولة مجددًا أو دخول التطبيق بأمان.","onboarding.library.achievementsLater":"يمكنك مزامنة الإنجازات لاحقًا من تفاصيل اللعبة أو إعدادات Steam.","onboarding.enter":"ادخل إلى Achievement Nexus","onboarding.saving":"جارٍ الحفظ…"
} as const;
