import type { Achievement, Game, PlayerActivity, SyncMetadata, UserProfile } from "../../types";

export interface GameRecord { id:string; platformId:string; platformGameId:string; name:string; coverUrl:string; backgroundUrl:string; playtimeMinutes:number; achievementsUnlocked:number; achievementsTotal:number; completionPercentage:number; lastPlayedAt:string|null; playtimeTwoWeeksMinutes:number|null; playtimeWindowsMinutes:number|null; playtimeMacMinutes:number|null; playtimeLinuxMinutes:number|null; iconUrl:string; syncedAt:string|null; favorite:boolean; hidden:boolean; gameStatus:NonNullable<Game["status"]> }
export interface AchievementRecord { id:string; gameId:string; platformAchievementId:string; name:string; description:string; iconUrl:string; isUnlocked:boolean; isHidden:boolean; rarityPercentage:number; unlockedAt:string|null }
export interface ActivityRecord { id:string; activityType:PlayerActivity["type"]; gameId:string|null; achievementId:string|null; title:string; description:string; progress:number|null; occurredAt:string }
export interface ProfileRecord { id:string; displayName:string; avatarUrl:string; activePlatform:string }
export interface SyncRecord { platformId:string; lastSyncAt:string|null; syncStatus:SyncMetadata["status"]; errorMessage:string|null }

export const gameToRecord = (game:Game):GameRecord => ({ id:game.id,platformId:game.platform,platformGameId:game.appId,name:game.name,coverUrl:game.coverUrl,backgroundUrl:game.backgroundUrl,playtimeMinutes:Math.round(game.playtimeHours*60),achievementsUnlocked:game.unlockedAchievements,achievementsTotal:game.totalAchievements,completionPercentage:game.completionPercentage,lastPlayedAt:game.lastPlayedAt||null,playtimeTwoWeeksMinutes:game.playtimeTwoWeeksMinutes??null,playtimeWindowsMinutes:game.playtimeWindowsMinutes??null,playtimeMacMinutes:game.playtimeMacMinutes??null,playtimeLinuxMinutes:game.playtimeLinuxMinutes??null,iconUrl:game.iconUrl??"",syncedAt:game.syncedAt??null,favorite:Boolean(game.favorite),hidden:Boolean(game.hidden),gameStatus:game.status??(game.completionPercentage>=100?"completed":game.playtimeHours>0?"playing":"notStarted") });
export const recordToGame = (row:GameRecord):Game => ({ id:row.id,appId:row.platformGameId,platform:row.platformId as Game["platform"],name:row.name,coverUrl:row.coverUrl,backgroundUrl:row.backgroundUrl,playtimeHours:row.playtimeMinutes/60,totalAchievements:row.achievementsTotal,unlockedAchievements:row.achievementsUnlocked,completionPercentage:row.completionPercentage,lastPlayedAt:row.lastPlayedAt??"",playtimeTwoWeeksMinutes:row.playtimeTwoWeeksMinutes??undefined,playtimeWindowsMinutes:row.playtimeWindowsMinutes??undefined,playtimeMacMinutes:row.playtimeMacMinutes??undefined,playtimeLinuxMinutes:row.playtimeLinuxMinutes??undefined,iconUrl:row.iconUrl||undefined,syncedAt:row.syncedAt??undefined,favorite:row.favorite,hidden:row.hidden,status:row.gameStatus });
export const achievementToRecord = (item:Achievement):AchievementRecord => ({id:item.id,gameId:item.gameId,platformAchievementId:item.id,name:item.title,description:item.description,iconUrl:item.iconUrl,isUnlocked:Boolean(item.unlockedAt),isHidden:Boolean(item.isHidden),rarityPercentage:item.rarityPercentage,unlockedAt:item.unlockedAt??null});
export const recordToAchievement = (row:AchievementRecord):Achievement => ({id:row.id,gameId:row.gameId,title:row.name,description:row.description,iconUrl:row.iconUrl,unlockedAt:row.isUnlocked?row.unlockedAt??undefined:undefined,rarityPercentage:row.rarityPercentage,points:0,isHidden:row.isHidden});
export const activityToRecord = (item:PlayerActivity):ActivityRecord => ({id:item.id,activityType:item.type,gameId:item.gameId??null,achievementId:null,title:item.title,description:item.description,progress:item.metadata?Number.parseFloat(item.metadata) || null:null,occurredAt:item.occurredAt});
export const recordToActivity = (row:ActivityRecord):PlayerActivity => ({id:row.id,type:row.activityType,gameId:row.gameId??undefined,title:row.title,description:row.description,occurredAt:row.occurredAt,metadata:row.progress===null?undefined:String(row.progress)});
export const profileToRecord = (profile:UserProfile):ProfileRecord => ({id:profile.id,displayName:profile.displayName,avatarUrl:profile.avatarUrl,activePlatform:"steam"});
export const recordToProfile = (row:ProfileRecord):UserProfile => ({id:row.id,displayName:row.displayName,avatarUrl:row.avatarUrl,level:1});
