import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { inspectToolUrl } from "../src/features/tools/safeToolUrl.ts";
import { tools as enTools } from "../src/locales/en/tools.ts";
import { tools as arTools } from "../src/locales/ar/tools.ts";

const read = (path) => readFileSync(new URL(path, import.meta.url), "utf8");
const app = read("../src/App.tsx");
const sidebar = read("../src/components/layout/Sidebar.tsx");
const page = read("../src/pages/ToolsPage.tsx");
const card = read("../src/features/tools/ToolCard.tsx");
const image = read("../src/features/tools/ToolImage.tsx");
const details = read("../src/pages/ToolDetailsPage.tsx");
const client = read("../src/features/tools/ToolClient.ts");
const admin = read("../src/features/developer-center/tools/ToolsManagementPanel.tsx");
const css = read("../src/styles/index.css");
const rust = read("../src-tauri/src/lib.rs");

assert.match(sidebar, /id: "tools"/);
assert.match(app, /ToolDetailsPage/);
assert.match(card, /ToolImage/);
assert.match(image, /"lazy"/);
assert.match(image, /onError/);
assert.match(page, /toolsPage\./);
assert.match(page, /favoritesOnly/);
assert.match(page, /tools-tabs/);
assert.match(page, /tools-hero/);
assert.match(card, /ToolFavoriteButton/);
assert.match(card, /onFavoriteToggle/);
assert.match(card, /dir="auto"/);
assert.match(client, /method: active \? "PUT" : "DELETE"/);
assert.match(client, /favorite-status/);
assert.match(client, /authorization: `Bearer \$\{session\.token\}`/);
assert.match(css, /tools-hero/);
assert.match(css, /tool-favorite/);
assert.match(css, /tool-card:focus-visible/);
assert.doesNotMatch(page + details, /downloadCount|dangerouslySetInnerHTML/i);
assert.match(details, /role="dialog"/);
assert.match(details, /aria-modal="true"/);
assert.match(details, /invoke\("open_external_tool_url"/);
assert.match(admin, /type Mode/);
assert.match(css, /prefers-reduced-motion:reduce/);
assert.match(css, /forced-colors:active/);
assert.match(rust, /validate_external_tool_url/);
assert.deepEqual(Object.keys(enTools).sort(), Object.keys(arTools).sort());
const publicCopy = Object.entries(enTools).filter(([key]) => key.startsWith("tools.")).map(([, value]) => value).join(" ");
assert.doesNotMatch(publicCopy, /\b(?:API|Database|Backend|Storage|Endpoint|Status Code|Token|Manifest)\b/i);
assert.equal(inspectToolUrl("https://example.com/tool").domain, "example.com");
for (const value of ["javascript:alert(1)", "data:text/plain,x", "file:///tmp/x", "http://example.com", "https://localhost/x", "https://127.0.0.1/x", "https://10.0.0.1/x", "https://100.64.0.1/x", "https://[::1]/x", "https://user:pass@example.com/x", "https://аррӏе.example/x", "https://xn--80ak6aa92e.example/x", "https://example.com:8443/x", "not a url"]) assert.throws(() => inspectToolUrl(value));
console.log("Nexus Tools UX and external URL validation passed.");
