import type{IncomingMessage,ServerResponse}from"node:http";import{AuthorizationError}from"../authorization/contracts.ts";import type{AuthorizationService}from"../authorization/authorizationService.ts";import type{SessionTokenService}from"../authorization/sessionTokenService.ts";import{ToolError}from"../tools/contracts.ts";import{parseToolBadge,parseToolCategory,parseToolQuery,type ToolService}from"../tools/toolService.ts";
type Deps={tools:ToolService;authorization:AuthorizationService;sessions:SessionTokenService};
export function isToolPath(p:string){return p==="/api/tools"||/^\/api\/tools\/[a-z0-9-]+$/.test(p)||p.startsWith("/api/admin/tools")||p.startsWith("/api/admin/tool-badges")||p.startsWith("/api/admin/tool-categories");}
export async function handleTools(req:IncomingMessage,res:ServerResponse,url:URL,d:Deps){if(!isToolPath(url.pathname))return false;let actor:string|undefined;try{
 if(url.pathname==="/api/tools"&&req.method==="GET"){const q=parseToolQuery(url.searchParams);return json(res,200,{...(await d.tools.list(q)),page:q.page,pageSize:q.pageSize});}
 const publicMatch=url.pathname.match(/^\/api\/tools\/([a-z0-9-]+)$/);if(publicMatch&&req.method==="GET"){const x=await d.tools.getBySlug(publicMatch[1]);if(!x)throw new ToolError("TOOL_NOT_FOUND");return json(res,200,x);}
 const user=await d.sessions.authenticateBearer(typeof req.headers.authorization==="string"?req.headers.authorization:undefined);actor=user.id;
 if(url.pathname==="/api/admin/tools"&&req.method==="GET"){await d.authorization.requirePermission(actor,"tools.manage");const q=parseToolQuery(url.searchParams,true);return json(res,200,{...(await d.tools.list(q)),page:q.page,pageSize:q.pageSize});}
 if(url.pathname==="/api/admin/tools"&&req.method==="POST"){await d.authorization.requirePermission(actor,"tools.manage");return json(res,201,await d.tools.create(await body(req),actor));}
 const tool=url.pathname.match(/^\/api\/admin\/tools\/([0-9a-f-]+)(?:\/(archive|reactivate))?$/i);if(tool){await d.authorization.requirePermission(actor,"tools.manage");if(req.method==="PATCH"&&!tool[2])return json(res,200,await d.tools.update(tool[1],await body(req),actor));if(req.method==="POST"&&tool[2])return json(res,200,tool[2]==="archive"?await d.tools.archive(tool[1],actor):await d.tools.reactivate(tool[1],actor));}
 if(url.pathname==="/api/admin/tool-badges"&&req.method==="GET"){await d.authorization.requirePermission(actor,"tool_badges.manage");return json(res,200,{items:await d.tools.badges.list(url.searchParams.get("archived")==="true")});}
 if(url.pathname==="/api/admin/tool-badges"&&req.method==="POST"){await d.authorization.requirePermission(actor,"tool_badges.manage");return json(res,201,await d.tools.badges.create(parseToolBadge(await body(req)),actor));}
 const badge=url.pathname.match(/^\/api\/admin\/tool-badges\/([0-9a-f-]+)(?:\/(archive|reactivate))?$/i);if(badge){await d.authorization.requirePermission(actor,"tool_badges.manage");if(req.method==="PATCH"&&!badge[2])return json(res,200,await d.tools.badges.update(badge[1],parseToolBadge(await body(req)),actor));if(req.method==="POST"&&badge[2])return json(res,200,await d.tools.badges.setArchived(badge[1],badge[2]==="archive",actor));}
 if(url.pathname==="/api/admin/tool-categories"&&req.method==="GET"){await d.authorization.requirePermission(actor,"tool_categories.manage");return json(res,200,{items:await d.tools.categories.list(url.searchParams.get("archived")==="true")});}
 if(url.pathname==="/api/admin/tool-categories"&&req.method==="POST"){await d.authorization.requirePermission(actor,"tool_categories.manage");return json(res,201,await d.tools.categories.create(parseToolCategory(await body(req)),actor));}
 const category=url.pathname.match(/^\/api\/admin\/tool-categories\/([0-9a-f-]+)(?:\/(archive|reactivate))?$/i);if(category){await d.authorization.requirePermission(actor,"tool_categories.manage");if(req.method==="PATCH"&&!category[2])return json(res,200,await d.tools.categories.update(category[1],parseToolCategory(await body(req)),actor));if(req.method==="POST"&&category[2])return json(res,200,await d.tools.categories.setArchived(category[1],category[2]==="archive",actor));}
 return json(res,405,{error:"METHOD_NOT_ALLOWED"});
}catch(e){if(e instanceof AuthorizationError&&actor)await d.authorization.repository.writeAuditEvent({actorUserId:actor,action:"tool.action_denied",targetType:"tool",metadata:{path:url.pathname,method:req.method??"UNKNOWN"}}).catch(()=>{});const code=e instanceof ToolError||e instanceof AuthorizationError?e.code:e instanceof Error&&e.message.includes("slug")?"TOOL_SLUG_CONFLICT":"TOOL_OPERATION_FAILED";const status=code==="AUTHENTICATION_REQUIRED"?401:code==="PERMISSION_DENIED"?403:code.endsWith("NOT_FOUND")?404:code.includes("CONFLICT")||code==="TOOL_METADATA_IN_USE"?409:code==="TOOL_OPERATION_FAILED"?500:400;return json(res,status,{error:code});}}
async function body(req:IncomingMessage){const chunks:Buffer[]=[];let n=0;for await(const c of req){n+=c.length;if(n>128*1024)throw new ToolError("INVALID_TOOL");chunks.push(c);}try{return JSON.parse(Buffer.concat(chunks).toString("utf8"));}catch{throw new ToolError("INVALID_JSON");}}
function json(res:ServerResponse,status:number,p:object){const b=JSON.stringify(p);res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":status===200?"public, max-age=60, stale-while-revalidate=120":"no-store","x-content-type-options":"nosniff","content-length":Buffer.byteLength(b)});res.end(b);return true;}
